### ISSUE TITLE
Search within snippet contents

### ISSUE THREAD

**Issue by fhill2** [out-of-cheese-error/the-way#115]
As a `pet` user, searching snippet contents/body & descriptions at the same time in the same `fzf` pane interactively helps me find the snippet I'm looking for faster.
Sometimes I remember a part of the snippet contents and not the description, and vice versa.

So far I have been using ([PR #68](https://github.com/out-of-cheese-error/the-way/pull/68) that searches contents and descriptions, but it is not interactive.
(afaik) there is no feature to perform an interactive grep on snippet contents.

What are your thoughts about adding such a feature?

**Comment by Ninjani** [comment]
Nice idea and would be really useful!

This ended up being not that hard to implement at a basic level - PR #116 lets you search also within snippet contents but it doesn't highlight the matching text within the code preview. To add this I think the only way at the moment would be to run the search again within the code and redo the highlighting - I need to see how much this would impact performance since it adds an extra search and highlight step at each keypress. Maybe there's a workaround.

Also, I noticed that fuzzy search isn't that great for this purpose (returns a lot of false positives) so the PR has exact mode on - I'll make fuzzy an optional argument instead

**Comment by fhill2** [comment]
Thank you for implementing this feature.

I'm trying to test and having some issues.

Here's what I'm doing:

```shell
git clone https://github.com/out-of-cheese-error/the-way
git checkout -b search_code
cargo build
./target/debug/the-way search
# <enter phrase contained within a snippet>
```

Tried with `cargo build --release`, and the master branch.

To confirm, this change is implemented inside `the-way search` skim UI?
Not sure why I'm not seeing the expected changes you have described.

**Comment by Ninjani** [comment]
I think the command would be `git clone -b search_code https://github.com/out-of-cheese-error/the-way`, git checkout would make a new local branch instead.

Also, I've added the -e option for exact matching and kept fuzzy as default.

**Comment by fhill2** [comment]
Aah haha yeah my bad, been a long day.
All working now on my system.

This is awesome, search is within body and description language tag now with the same result highlighting.

It is snappy however I only have around 10 snippets.

**Comment by Ninjani** [comment]
Great to hear, thanks! I'll test it out tomorrow with 100 random gists and then push a new version.
