### ISSUE TITLE
Any chance of getting a human readable DB? 

### ISSUE THREAD

**Issue by seivan** [out-of-cheese-error/the-way#120]
Pet seems to no longer be maintained and is plagued by bugs and lacks configuration.
But one of it strength is the human readable snippets `toml` files that can be edited. 
I only use it for shell snippets, since docker is a nightmare. One of my use cases is actually editing the toml file directly in sublime for what I need. 

Is there a way to do that now, or is that some extensive work?

**Comment by Ninjani** [comment]
Since the-way supports any language and snippets of any size I imagine a `toml` file would get unwieldy pretty fast for people who don't only have shell snippets. 

I agree that a human readable single file or set of files would be useful though, especially if you want to make similar changes across many snippets at once. One possibility that already exists is to sync to a Gist and edit the Gist instead (this can be done [locally](https://gist.github.com/DannyQuah/5f43f9b75970bc4e357e42c7c9214b5d) as well). Is this something that could make sense for your use case?

**Comment by seivan** [comment]
> One possibility that already exists is to sync to a Gist and edit the Gist instead (this can be done [locally](https://gist.github.com/DannyQuah/5f43f9b75970bc4e357e42c7c9214b5d) as well). Is this something that could make sense for your use case?

Sorry for the delay.

No that solution would be too cumbersome. Inherently I'd like whatever I am using to store snippets to be human readable on the off chance the program is no longer supported and it would be easy for me to just grep. Just a policy, thanks anyway.
