### ISSUE TITLE
Documentation: What is the number in the top-right of the search interface?

### ISSUE THREAD

**Issue by daturkel** [out-of-cheese-error/the-way#46]
When I `the-way search` and browse through snippets, the top-left corner has something like `1/4`, `1/7`. What do these mean?

**Comment by Ninjani** [comment]
This is a `skim` feature, it shows the `line_num/total_line_num` of the text in the preview (the code in this case), to let the user know the current offset. Scrolling the top panel should increase the offset. I'm guessing this won't usually be used since snippets are generally small and the code preview panel is 60% of the screen - though maybe this 60% could be customizable, what do you think?.

**Comment by daturkel** [comment]
The line number of the preview had been my original guess but I notice that it always seems to add a few lines—for my one-line snippets, for example, it's always 1/4. I also couldn't figure out how to scroll the snippet other than using the trackpad gesture (is there a keyboard shortcut?).

And I think the 60% looks good as-is, personally!

**Comment by Ninjani** [comment]
I noticed that too and realized it's because of the new lines added to separate one snippet from another in `the-way list` - I've moved these new lines out of the search preview code now, in PR #48 so the numbers should be correct in the next release, thanks for bringing it to my attention! 

About the scroll - you can also use shift+[down|up] instead of the mouse / trackpad but this doesn't scroll line by line, it goes immediately to the next page. 

Good to hear that 60% looks fine for other workflows too! If left to my own devices I would end up making everything customizable which would probably be overkill for something as simple as this.

**Comment by daturkel** [comment]
Thanks for the quick fix and being so responsive! I'd contribute but I don't know a thing about Rust.
