### ISSUE TITLE
Sync and backup of database

### ISSUE THREAD

**Issue by omertuc** [out-of-cheese-error/the-way#52]
The database directory contains several files:

![image](https://user-images.githubusercontent.com/10882062/82120380-3f37e780-978e-11ea-8ced-d51517d7f91c.png)

I want to sync/backup the database across several machines, which of these files are important enough needs to be backed up for it to work? My current guess is that `db` should be enough, but the `snap.*` and `conf` also seem important. `blobs` is currently empty.

Could you please explain what these files are? And for future users - maybe add a README.md to that directory to help guide people who'll wonder the same.

**Comment by Ninjani** [comment]
The Way uses [sled](https://github.com/spacejam/sled) for database support. I skimmed sled's repo a bit and came to the conclusion that `db` and `conf` (which is the config file for the database) are the required files for backup. From what I could understand, `blobs` are for recovering data in a big database if it gets corrupted, and `snap.*` are snapshots to speed up the database initialization, so I don't think these are needed. I've asked this question over at their Discord to double check and I'll get back to you once they reply.

Good idea about adding a README; I'll do that after confirming that backing up works with these files, thanks!

**Comment by Ninjani** [comment]
Okay, got a reply from the `sled` maintainer and they say you need all the files for a valid backup. I hope that answers your question. I believe some aspects of `sled` are going to change in the 1.0 release so I think I would prefer to keep this directory as a black box for now. Similarly, if users would need to migrate to a backward-incompatible version of `sled` I think it would make more sense to run `the-way export`, `the-way clear` and `the-way import` instead of expecting users to have to deal with db migration themselves. What do you think?

**Comment by omertuc** [comment]
Thank you for your effort.

I didn't realize there was `the-way {export,clear,import}`. That's great! I definitely agree users should rely on that rather than trying to sync the black-box database themselves. That's what I'll do from now on.

Great project by the way, up until now I've been sending my self Slack messages, but this is much nicer.

**Comment by Ninjani** [comment]
Thank you, that's great to hear! Let me know if you come up with possible enhancements / features for your workflow.
