### ISSUE TITLE
Panic after adding an Elixir snippet

### ISSUE THREAD

**Issue by meluskyc** [out-of-cheese-error/the-way#56]
It seems the `txt` fallback is not working for me.

Steps to reproduce: 
- `the-way new`
- Add a snippet for a language without syntax highlight support e.g. Elixir
- `the-way search`

Using `find_syntax_by_extension("txt")` instead of `find_syntax_by_extension(".txt")` seems to fix it.

**Comment by Ninjani** [comment]
Thanks! Fixed in v0.3.2, could you take a look? 

I'm thinking of overhauling the syntax highlighting part so that you can also add Sublime highlighting files for the non-default languages like Elixir and Kotlin but it'll be a while before I can find time for this. 

This is probably fine as a workaround until I get around to that!

**Comment by meluskyc** [comment]
Fixed for me. Thanks!
