### ISSUE TITLE
poor readability of highlighted item in light themes

### ISSUE THREAD

**Issue by vbauerster** [out-of-cheese-error/the-way#58]
Hello! I've tried all built-in light themes and they all suffer same issue, that is poor readability of highlighted item in fuzzy pane. Following is `InspiredGitHub` theme, but others light themes have more or less same issue.

[![Screenshot-2020-07-02-at-20-43-32.png](https://i.postimg.cc/qq5bTd8j/Screenshot-2020-07-02-at-20-43-32.png)](https://postimg.cc/D41drHpX)

**Comment by Ninjani** [comment]
Hi! It looks like this can be fixed by fiddling around with the [color scheme](https://github.com/lotabout/skim/blob/065d03a44838e118657795514efbd2bd25abae54/man/man1/sk.1#L203) in `skim`. I'll try to link it to the code highlight theme so everything is consistent. Thanks for bringing this to my attention, will push a fix this week.

**Comment by Ninjani** [comment]
Should be fixed in [v0.4.0](https://github.com/out-of-cheese-error/the-way/releases/latest). Could you try and see if it looks better for you?

**Comment by vbauerster** [comment]
It's definitely better now. Thank you!

[![Screenshot-2020-07-04-at-19-05-50.png](https://i.postimg.cc/R0HJ52d7/Screenshot-2020-07-04-at-19-05-50.png)](https://postimg.cc/SXmxcTwR)

**Comment by Ninjani** [comment]
Great! Closing the issue then :)
