### ISSUE TITLE
the-way search: add option to use stderr for interface, directly output snippet

### ISSUE THREAD

**Issue by kaspar030** [out-of-cheese-error/the-way#93]
When using the-way in the shell using `the-way search`, finding a snippet is very convenient, but then it gets copied to the clipboard.

I'd much prefer an option that would just output the snippet to stdout. That way I could bind the-way to some key combination in bash and then directly get the snippet on the command line, maybe even automatically pressing enter.
That would probably require the interface of the-way to print to stderr.

**Comment by kaspar030** [comment]
BTW, this is how some command line fuzzy searchers, e.g., [fzf](https://github.com/junegunn/fzf), integrate in shells.

**Comment by Ninjani** [comment]
This is a great idea but would only make sense for shell snippets, `the-way` stores snippets from any language. I'll look into adding this as an extra keyboard shortcut in search (and maybe also as a command `the-way run <index>`) but will have to think a bit about what should happen if the shortcut is pressed on non-shell snippets - does nothing, throws a warning, just copies to clipboard? Thoughts?

**Comment by kaspar030** [comment]
Outputting to stdout in "search" would be useful for any language.

1. I'd use it as a (ba)sh binding like `the-way search --languages shell --stdout`
2. I'd use it in vim as a binding, where vim's filetype decides the language parameter.

I think if the-way is called with the "output to stdout" parameter and a snippet for a non-shell language is selected, maybe the user actually wants that.

**Comment by Ninjani** [comment]
I had some time to look into this today, fzf seems to do this with key bindings specific to each shell (more info [here](https://github.com/junegunn/fzf#key-bindings-for-command-line) and [here for bash](https://github.com/junegunn/fzf/blob/master/shell/key-bindings.bash)) and a separate plugin for vim. It's a bit harder than it seems because the expected behavior is not printing to stdout (which would just print and not allow you to edit/execute the command) but instead append to the editing buffer.

I'll try to see if I can set something like this up for `the-way` on the shell. I've never worked with VimScript before, but maybe it's easy to adapt fzf's to also make the vim plugin, I'll take a look.

**Comment by Ninjani** [comment]
This is coming up in the next release today as a flag attached to the copy and search commands. Ideally later on I'll add keybindings for popular shells like fzf does.

**Comment by Ninjani** [comment]
Added in v0.13.0
